---
abstract: 'Display information about POE sessions and events'
author:
  - 'Sebastien Aperghis-Tramoni <sebastien@aperghis.net>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.120921'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: POE-Devel-Top
no_index:
  directory:
    - t
    - inc
requires:
  POE: 0
  POE::API::Peek: 0
  Term::ANSIColor: 0
  Test::More: 0
version: 0.100
